// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TroskoviRada.Data;

#nullable disable

namespace TroskoviRada.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118144029_PromjenaSmjena4")]
    partial class PromjenaSmjena4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TroskoviRada.Models.Naknada", b =>
                {
                    b.Property<int>("IdNaknada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNaknada"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("IdTipNaknade")
                        .HasColumnType("integer");

                    b.Property<int>("IdZaposlenik")
                        .HasColumnType("integer");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ZaposlenikIdZaposlenik")
                        .HasColumnType("integer");

                    b.HasKey("IdNaknada");

                    b.HasIndex("IdTipNaknade");

                    b.HasIndex("IdZaposlenik");

                    b.HasIndex("ZaposlenikIdZaposlenik");

                    b.ToTable("naknada", (string)null);
                });

            modelBuilder.Entity("TroskoviRada.Models.Obračun", b =>
                {
                    b.Property<int>("IdObračun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObračun"));

                    b.Property<decimal>("BrutoPlaca")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("DatumObračuna")
                        .HasColumnType("date");

                    b.Property<int>("Godina")
                        .HasColumnType("integer");

                    b.Property<int>("IdZaposlenik")
                        .HasColumnType("integer");

                    b.Property<bool>("Isplaceno")
                        .HasColumnType("boolean");

                    b.Property<int>("Mjesec")
                        .HasColumnType("integer");

                    b.Property<string>("Napomene")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("NetoPlaca")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Osnovica")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Porez")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("UkupneNaknade")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("IdObračun");

                    b.HasIndex("IdZaposlenik");

                    b.ToTable("obracun", null, t =>
                        {
                            t.HasTrigger("trg_obracun_history");
                        });
                });

            modelBuilder.Entity("TroskoviRada.Models.Odsustvo", b =>
                {
                    b.Property<int>("IdOdsustvo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odsustvo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdsustvo"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("date")
                        .HasColumnName("datum_do");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("date")
                        .HasColumnName("datum_od");

                    b.Property<int>("IdTipOdsustva")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_odsustva");

                    b.Property<int>("IdZaposlenik")
                        .HasColumnType("integer")
                        .HasColumnName("id_zaposlenik");

                    b.Property<bool>("Odobreno")
                        .HasColumnType("boolean")
                        .HasColumnName("odobreno");

                    b.Property<string>("Razlog")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("razlog");

                    b.Property<int?>("TipOdsustvaIdTipOdsustva")
                        .HasColumnType("integer");

                    b.Property<int?>("ZaposlenikIdZaposlenik")
                        .HasColumnType("integer");

                    b.HasKey("IdOdsustvo");

                    b.HasIndex("IdTipOdsustva");

                    b.HasIndex("IdZaposlenik");

                    b.HasIndex("TipOdsustvaIdTipOdsustva");

                    b.HasIndex("ZaposlenikIdZaposlenik");

                    b.ToTable("odsustvo", (string)null);
                });

            modelBuilder.Entity("TroskoviRada.Models.Prisustvo", b =>
                {
                    b.Property<int>("IdPrisustvo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrisustvo"));

                    b.Property<decimal?>("BrojSati")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("IdSmjena")
                        .HasColumnType("integer");

                    b.Property<int>("IdZaposlenik")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("UkupnoOdradeno")
                        .HasColumnType("numeric(5,2)");

                    b.Property<TimeSpan>("VrijemeDolaska")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("VrijemeOdlaska")
                        .HasColumnType("time");

                    b.HasKey("IdPrisustvo");

                    b.HasIndex("IdSmjena");

                    b.HasIndex("IdZaposlenik");

                    b.ToTable("evidencija_rada", null, t =>
                        {
                            t.HasTrigger("trg_evidencija_rada_history");
                        });
                });

            modelBuilder.Entity("TroskoviRada.Models.RadnoMjesto", b =>
                {
                    b.Property<int>("IdRadnoMjesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRadnoMjesto"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Satnica")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdRadnoMjesto");

                    b.ToTable("radno_mjesto", null, t =>
                        {
                            t.HasTrigger("trg_radno_mjesto_history");
                        });
                });

            modelBuilder.Entity("TroskoviRada.Models.Smjena", b =>
                {
                    b.Property<int>("IdSmjena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSmjena"));

                    b.Property<decimal>("KoeficijentPlacanja")
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("NazivSmjene")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeSpan>("VrijemePocetka")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("VrijemeZavrsetka")
                        .HasColumnType("interval");

                    b.HasKey("IdSmjena");

                    b.ToTable("smjena", (string)null);
                });

            modelBuilder.Entity("TroskoviRada.Models.TipNaknade", b =>
                {
                    b.Property<int>("IdTipNaknade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipNaknade"));

                    b.Property<decimal>("Iznos")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("JePostotak")
                        .HasColumnType("boolean");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdTipNaknade");

                    b.ToTable("tip_naknade", (string)null);
                });

            modelBuilder.Entity("TroskoviRada.Models.TipOdsustva", b =>
                {
                    b.Property<int>("IdTipOdsustva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_odsustva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipOdsustva"));

                    b.Property<decimal>("KoeficijentIsplate")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("koeficijent_isplate");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tip");

                    b.HasKey("IdTipOdsustva");

                    b.ToTable("tip_odsustva", (string)null);
                });

            modelBuilder.Entity("TroskoviRada.Models.Zaposlenik", b =>
                {
                    b.Property<int>("IdZaposlenik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZaposlenik"));

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Oib")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdZaposlenik");

                    b.ToTable("zaposlenik", null, t =>
                        {
                            t.HasTrigger("trg_zaposlenik_history");
                        });
                });

            modelBuilder.Entity("TroskoviRada.Models.Zaposlenje", b =>
                {
                    b.Property<int>("IdZaposlenje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZaposlenje"));

                    b.Property<DateTime?>("DatumDo")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("date");

                    b.Property<int>("IdRadnoMjesto")
                        .HasColumnType("integer");

                    b.Property<int>("IdZaposlenik")
                        .HasColumnType("integer");

                    b.HasKey("IdZaposlenje");

                    b.HasIndex("IdRadnoMjesto");

                    b.HasIndex("IdZaposlenik");

                    b.ToTable("zaposlenje", (string)null);
                });

            modelBuilder.Entity("TroskoviRada.Models.Naknada", b =>
                {
                    b.HasOne("TroskoviRada.Models.TipNaknade", "TipNaknade")
                        .WithMany()
                        .HasForeignKey("IdTipNaknade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_naknada_tip_naknade");

                    b.HasOne("TroskoviRada.Models.Zaposlenik", "Zaposlenik")
                        .WithMany()
                        .HasForeignKey("IdZaposlenik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_naknada_zaposlenik");

                    b.HasOne("TroskoviRada.Models.Zaposlenik", null)
                        .WithMany("Naknade")
                        .HasForeignKey("ZaposlenikIdZaposlenik");

                    b.Navigation("TipNaknade");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("TroskoviRada.Models.Obračun", b =>
                {
                    b.HasOne("TroskoviRada.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("Obračuni")
                        .HasForeignKey("IdZaposlenik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obracun_zaposlenik");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("TroskoviRada.Models.Odsustvo", b =>
                {
                    b.HasOne("TroskoviRada.Models.TipOdsustva", "TipOdsustva")
                        .WithMany()
                        .HasForeignKey("IdTipOdsustva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_odsustvo_tip_odsustva");

                    b.HasOne("TroskoviRada.Models.Zaposlenik", "Zaposlenik")
                        .WithMany()
                        .HasForeignKey("IdZaposlenik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_odsustvo_zaposlenik");

                    b.HasOne("TroskoviRada.Models.TipOdsustva", null)
                        .WithMany("Odsustva")
                        .HasForeignKey("TipOdsustvaIdTipOdsustva");

                    b.HasOne("TroskoviRada.Models.Zaposlenik", null)
                        .WithMany("Odsustva")
                        .HasForeignKey("ZaposlenikIdZaposlenik");

                    b.Navigation("TipOdsustva");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("TroskoviRada.Models.Prisustvo", b =>
                {
                    b.HasOne("TroskoviRada.Models.Smjena", "Smjena")
                        .WithMany()
                        .HasForeignKey("IdSmjena");

                    b.HasOne("TroskoviRada.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("Prisustva")
                        .HasForeignKey("IdZaposlenik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evidencija_rada_zaposlenik");

                    b.Navigation("Smjena");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("TroskoviRada.Models.Zaposlenje", b =>
                {
                    b.HasOne("TroskoviRada.Models.RadnoMjesto", "RadnoMjesto")
                        .WithMany()
                        .HasForeignKey("IdRadnoMjesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_zaposlenje_radno_mjesto");

                    b.HasOne("TroskoviRada.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("Zaposlenja")
                        .HasForeignKey("IdZaposlenik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zaposlenje_zaposlenik");

                    b.Navigation("RadnoMjesto");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("TroskoviRada.Models.TipOdsustva", b =>
                {
                    b.Navigation("Odsustva");
                });

            modelBuilder.Entity("TroskoviRada.Models.Zaposlenik", b =>
                {
                    b.Navigation("Naknade");

                    b.Navigation("Obračuni");

                    b.Navigation("Odsustva");

                    b.Navigation("Prisustva");

                    b.Navigation("Zaposlenja");
                });
#pragma warning restore 612, 618
        }
    }
}
